# Generated by Django 4.1.7 on 2023-04-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50)),
                ('quantidade', models.CharField(max_length=50)),
                ('preco', models.CharField(max_length=50)),
            ],
        ),
    ]
